- .github/workflows/publication-npm.yml
- package.json
Cette PR vise à permettre la publication du https://www.npmjs.com/ d'un package `@lab-anssi/ui-kit`.
On veut publier via une Github action.
> [NPM] Ajoute le workflow de publication sur NPM

- .github/workflows/publication-storybook.yml
- histoire.config.ts
... afin de publier notre Storybook.
> [CI/CD] Ajoute une action de déploiement du storybook

- outils/vite-plugin-genere-jsx.ts
... dans la génération du fichier JSX.
> Prend en compte le cas des composants sans "props"

- .github/workflows/publication-npm.yml
… lors de la release d'une nouvelle version de l'UI Kit.
> [PUBLICATION] Rajoute la publication des assets vers un CDN

- .env.production
- .github/workflows/publication-npm.yml
Cette corrige l'URL des assets en PROD, et la façon de les publier sur le CDN.
> Correction pour la publication des assets

- package.json
- src/lib/mes-services-cyber/bandeau/Bandeau.svelte
Cette PR change la façon dont le background est rendu.
Elle utilise `url-asset()` pour styliser depuis le CSS et non depuis des `<img>`.
> Bandeau avec tiling

- outils/vite-plugin-injecte-nonce.ts
- package.json
... plutôt que via un `data-attr`.
> Récupère le `nonce` via la propriété dédiée

- README.md
... pour afficher les dépendances.
> Met à jour le fichier README

- package-lock.json
- package.json
... pour préparer une release.
> [Version] Passe en 1.2.0

- package.json
Passe à la mineur supérieur suite aux corrections visuels.
> [VERSION] Passe en 1.2.2

- stories/Documentation.story.svelte
- stories/OutilSelecteurTheme.svelte
- stories/icones/IconeCopier.svelte
... pour l'instant, uniquement pour parler des variables CSS.
> Ajoute une page de documentation

- src/lib/CentreAide.svelte
- stories/CentreAide.story.svelte
... afin de permettre aux consommateurs de l'UI kit de réaliser des actions "sur-mesure".
> Fais remonter un évènement lors du clic sur un lien du centre d'aide

- package.json
... afin de livrer les nouvelles fonctionnalitées.
> [VERSION] Passe en 1.3.1

- package.json
- src/lib/suite-cyber/navigation/Navigation.svelte
> Supprime les liens vers les services Silene et ADS de la suite Cyber

- package-lock.json
- package.json
- src/lib/mes-services-cyber/lien/LienDiagnosticCyber.svelte
- stories/mes-services-cyber/lien/LienDiagnosticCyber.story.svelte
... En mobile on veut que le "bouton" prenne tout l'espace disponible et redimensionne la police.
> [CORRECTION] Corrige l'affichage du lien diagnostic cyber en version mobile/tablette

- .gitignore
- package-lock.json
- package.json
- src/lib/mes-services-cyber/lien/LienDiagnosticCyber.svelte
Dans le composant LienDiagnosticCyber, et passe en version 1.6.4.
> Parle d'aidant **cyber** plutôt que d'aidant de la communauté

- package-lock.json
- package.json
- src/lib/lab/vitrines-produits/briques/BriqueHero.svelte
- pour pouvoir s'en servir en webcomponent
> [SOIN] Renomme les props actionGauche et actionDroite sans de majuscules

- .github/workflows/integration-continue.yml
- stories/lab/vitrines-produits/LandingMAC.story.svelte
- stories/lab/vitrines-produits/LandingMSC.story.svelte
- stories/lab/vitrines-produits/LandingMSS.story.svelte
- stories/lab/vitrines-produits/briques/BriqueHero.story.svelte
- stories/lab/vitrines-produits/donneesProduits.ts
- et vérifie la construction du storybook en CI
> Corrige l'utilisation des propriétés des boutons d'action en camelcase pour la brique hero

- src/lib/lab/vitrines-produits/briques/Brique.svelte
- src/lib/lab/vitrines-produits/briques/CarrouselTuiles.svelte
- src/lib/lab/vitrines-produits/briques/Tuile.svelte
… afin de coller à la maquette des designers.
> [CORRECTION] Ajuste les marges laterales et verticales du carrousel de tuiles

- src/lib/lab/vitrines-produits/briques/LecteurVideo.svelte
- stories/lab/vitrines-produits/LandingMAC.story.svelte
- stories/lab/vitrines-produits/briques/BriqueTitreMultimedia.story.svelte
… afin de coller au maquette des designers.
> [CORRECTION] Adapte la largeur de la vidéo en fonction d'une taille maximale

- package-lock.json
- package.json
Cette montée de version embarquera : 
- la nouvelle brique Titre + Vidéo
- la marelle
> [VERSION] Passe à la version 1.9.0

- src/lib/lab/icones/LienExterne.svelte
- src/lib/lab/vitrines-produits/briques/BriqueHero.svelte
- src/lib/lab/vitrines-produits/briques/PresentationANSSI.svelte
- src/lib/lab/vitrines-produits/briques/marelle/Etape.svelte
- src/lib/lab/vitrines-produits/briques/marelle/Marelle.svelte
- src/lib/types.ts
- stories/exemples-integration/LandingMAC.story.svelte
> Rajoute une icone LienExterne lorsqu'un lien possède une target _blank

- src/lib/lab/vitrines-produits/briques/BriqueHero.svelte
- src/lib/lab/vitrines-produits/briques/CarrouselTuiles/CarrouselTuiles.svelte
- src/lib/lab/vitrines-produits/briques/PresentationANSSI.svelte
- src/lib/lab/vitrines-produits/briques/marelle/Etape.svelte
- src/lib/lab/vitrines-produits/briques/temoignages/Temoignages.svelte
Les briques impactées :
- Brique Hero
- Brique PrésentationANSSI
> [COMPOSANTS] Centre les libellés de boutons pour deux briques

- package-lock.json
- package.json
- src/lib/assets/icones/fleche-basse-noir.svg
- src/lib/index.ts
- src/lib/lab/blog/BandeauTitre.svelte
- src/lib/lab/blog/CarteArticle.svelte
- src/lib/lab/blog/ListeArticles.svelte
- src/lib/lab/blog/ListeDeroulante.svelte
- src/lib/lab/blog/Tag.svelte
- src/lib/lab/icones/Fleche.svelte
- src/lib/types.ts
- src/variables.scss
- stories/OutilSelecteurTheme.svelte
- stories/lab/blog/ListeArticles.story.svelte
... permettant d'afficher tous les articles dans une grille.
> [COMPOSANT] Ajout de la "Liste des articles"

- .github/workflows/publication-storybook-dev.yml
- histoire.config.ts
- package.json
- scripts/s3put_avec_le_bon_mime_type.sh
… du storybook. 
Cela nous permettra de faire un recettage des composants avec les designers, avant de faire une release de l'UI Kit.
> Ajoute une Github Actions permettant de déployer un environnement de "DEV"

- package-lock.json
- package.json
- src/lib/Alerte.svelte
- stories/Alerte.story.svelte
Cette pull request rajoute : 
- la police Marianne sur l'Alerte
- la possibilité de masquer le bouton de fermeture
> [ALERTE] Améliore le composant

- package-lock.json
- package.json
- src/lib/lab/Bouton.svelte
- src/lib/lab/Icone.svelte
- src/lib/lab/Lien.svelte
- src/lib/lab/apparence-bouton.scss
- src/variables.scss
- stories/OutilSelecteurTheme.svelte
- stories/lab/Bouton.story.svelte
- stories/lab/Lien.story.svelte
...avec les tailles petites, moyennes et grandes 
Le lien est également mis à jour pour pouvoir s’afficher comme le bouton.
> Fournis la variante primaire du bouton

- package-lock.json
- package.json
- src/lib/lab/apparence-bouton.scss
... et des liens qui ont l’apparence de boutons.
> Centre le contenu des boutons

- .storybook/styles.fonts.css
Cette PR implémente l'ajout de la police **Marianne** de façon globale à toutes les stories.
> Ajoute la police 'Marianne' de façon globale à toutes les stories

- stories_storybook/BriqueContenuADeuxColonnes.stories.ts
- stories_storybook/BriqueHero.stories.ts
- stories_storybook/BriqueTitreMultimedia.stories.ts
- stories_storybook/CarrouselTuiles.stories.ts
- stories_storybook/PresentationANSSI.stories.ts
- stories_storybook/RejoindreLaCommunaute.stories.ts
Cette PR ajoute les stories des composants du "Sites Vitrines", à savoir : 
- Composant `BriqueContenuADeuxColonnes`
- Composant `BriqueHero`
- Composant `BriqueTitreMultimedia`
- Composant `RejoindreLaCommunaute`
- Composant `CarrouselDeTuiles`
- Composant `PresentationANSSI`
> Ajoute les stories des composants "Sites Vitrines"

- .storybook/main.ts
- package-lock.json
- package.json
- src/lib/dsfr/DsfrAlert.svelte
- src/lib/dsfr/DsfrBadge.svelte
- src/lib/dsfr/DsfrButton.svelte
- src/lib/dsfr/DsfrContainer.svelte
- src/lib/utilitaires/index.ts
- stories/dsfr/Alert.stories.svelte
- stories/dsfr/Badge.stories.svelte
- stories/dsfr/Button.stories.svelte
- stories/dsfr/Container.stories.svelte
- vite.config.ts
Cette PR ajoute le DSFR en dépendance au projet afin de l'utiliser dans l'implémentation des composants
> [COMPOSANTS] - Ajoute les composants "Atomes" du DSFR

- package-lock.json
- package.json
Passe la version de l’UI Kit en 1.25.0
> [VERSION] Passe à la version 1.25.0

- src/lib/dsfr/DsfrButton.svelte
> [COMPOSANTS] Ajoute les styles au composant <dsfr-button>

- src/lib/composants/FiltresCatalogue.svelte
- src/lib/dsfr/DsfrButton.svelte
- src/lib/dsfr/DsfrCard.svelte
- src/lib/dsfr/DsfrInput.svelte
- src/lib/dsfr/DsfrSearch.svelte
- src/lib/dsfr/DsfrSelect.svelte
> Améliore les composants pour les rendre affichable dans DSC

- src/lib/composants/FiltresCatalogue.svelte
- src/lib/dsfr/DsfrInput.svelte
> Ameliorations

- .github/workflows/publication-npm.yml
- package-lock.json
- package.json
... vers le S3, afin de la versionner et rendre disponible aux consommateurs
On ajoute le déploiement de la feuille "variables.css" du DSFR vers notre S3.
> Construis et déploie la feuille de styles des variables du DSFR

- package-lock.json
- package.json
> [VERSION] Passe en version 1.29.3
