outils/vite-plugin-genere-jsx.ts
package.json
vite.config.ts
vite.webcomponents.config.ts

... pour React.
Afin de satisfaire le compilateur React, il faut déclarer les types de nos webcomponents sous ce format :
```ts
declare namespace JSX {
interface IntrinsicElements {
"mon-composant": {
maProps?: "conforme"|"nonConforme";
};
}
}
```
On écrit donc un plugin `vite` qui permet de générer ce fichier.
Il faut donc :
- Parser les fichiers "svelte" de la librairie pour obtenir le nom du webcomposant (contenu dans `<svelte:options customElement=`)
- Parser le fichier de type associé à ce composant pour en extraire les props
- Mettre en forme ces informations dans un fichier qui doit être publié via NPM

Ajoute le typage des webcomponents

---

outils/vite-plugin-genere-jsx.ts

... en utilisant le compilateur Typescript, et en le remettant en forme avec Prettier.
On en profite pour corrige un bug qui empêchait de générer les types pour les fichiers dans des sous-dossiers de "dist".

Vérifie le fichier `JSX` généré

---

src/assets.scss
vite.config.ts

…dans le code SCSS, permettant ainsi de définir des `background-url`, des `:before` ou autre.
S'utilise avec 
```scss
.selecteur {
background-url: chemin-asset('/mon/chemin/relatif')
}
```

Ajoute la possibilité d'utiliser la variable d'environnement de chemin d'assets

---

outils/vite-plugin-injecte-nonce.ts
vite.webcomponents.config.ts

Les webcomposants nous posent des problèmes de CSP, car ils injectent eux même des balises `<style>` dans le shadow DOM. Grâce à ce plugin, on ajoute un `nonce` à ces balises.
Ce nonce doit être passé lors de l'import du script via `data-nonce`.

Ajoute un outillage permettant d'injecter des `nonce` dans les balises de style

---

src/lib/suite-cyber/navigation/Navigation.svelte

Suite à des tests d'intégrations de la suite cyber sur les différentes applications de laboratoire de l'ANSSI, nous avons appliqué des correctifs visuels :
-  Force le police Marianne sur le bouton "fermer“ de la navigation en mode mobile
-  Ajoute un propriété au label de bouton de navigation "La Suite Cyber"  afin d'éviter qu'il passe sur plusieurs lignes
- Retire les guillemets variables de trackings UTM des liens de redirection vers les différents services depuis la Suite Cyber

Correctifs sur la suite cyber pour l'intégration dans les différentes applications du Lab 

---

stories/CentreAide.story.svelte

... car on utilise maintenant un `JSON.parse` pour les props complexes.

[CORRECTION] Corrige la story du centre d'aide

---

package-lock.json
package.json
src/lib/mes-services-cyber/lien/LienDiagnosticCyber.svelte
stories/mes-services-cyber/lien/LienDiagnosticCyber.story.svelte

... Afin de permettre au conteneur de determiner l'alignement du composant pour cela on le passe en 'inline-block' comme tout bouton html.

[CORRECTION] Corrige l'affichage du lien de diagnostic cyber

---

src/lib/lab/vitrines-produits/briques/Brique.svelte
src/variables.scss
stories/OutilSelecteurTheme.svelte
stories/lab/vitrines-produits/briques/Brique.story.svelte

L'idée pour ce composant `<Brique></Brique>` est de pouvoir obtenir un bloc dont le fond d'écran dépendrait du thème produit sélectionné, et d'y insérer n'importe quelle contenu (voir capture ci-dessous pour le thème MesServicesCyber)
L'utilisation du composant se ferait de cette façon : 
````
<Brique variation="primaire">
<slot />
</Brique>
````
NB : la variation primaire correspond au fond principal du produit (violet foncé pour MAC, le pattern pour MSC, ...)
Exemple avec le pattern MSC :
Exemple avec le fond MAC :

1. Créé un composant réutilisable Brique pour les pages vitrines

---

package-lock.json
package.json
src/lib/Alerte.svelte
src/lib/assets/icones/information.svg
src/lib/index.ts
stories/Alerte.story.svelte

On initie le composant Alerte dans un premier mode "Information" sans titre et avec bouton de fermeture. 
https://www.figma.com/design/6zxupO1ivYTw5qxzAyB0XZ/DSFR---Composants---LAB?node-id=1935-417&m=dev

Ajoute le composant Alerte en mode information

---

package-lock.json
package.json
src/lib/Alerte.svelte

On souhaite pour importer les composant en tant que WebComponents pour ne pas avoir de contrainte de language/framework dans les applications où ils sont utilisés.
Pour cela il faut bien penser à référencer le composant comme suivant:
`<svelte:options customElement="..."/>`

Expose le composant Alerte en tant que webcomponent 

---

src/lib/lab/vitrines-produits/briques/Brique.svelte
src/lib/lab/vitrines-produits/briques/BriqueHero.svelte
src/lib/types.ts
src/variables.scss
stories/OutilSelecteurTheme.svelte
stories/lab/vitrines-produits/LandingMAC.story.svelte
stories/lab/vitrines-produits/LandingMSC.story.svelte
stories/lab/vitrines-produits/LandingMSS.story.svelte
stories/lab/vitrines-produits/briques/BriqueHero.story.svelte
stories/lab/vitrines-produits/donneesProduits.ts

- une action est maintenant une balise `<a role="button" ...>` => Plus sémantique par rapport à son usage
- Les deux actions présentes dans la BriqueHero sont distinguée "actionGauche" & "actionDroite" pour permettre une stylisation plus simple
- La petite main au survol des boutons est rajoutée
- Le style des actions au survol change également
- L'icône de succes pour le badge "Service à impact national" est branchée sur la bonne fonction SASS pour s'afficher proprement sur les produits du lab
- Retire le calcul de la largeur sur le composant Brique car elle applique un scroll horizontal indésirable sur les produits
MSS :
MAC : 
MSC : 
`````
"brique-hero-bouton-gauche-background",
"brique-hero-bouton-gauche-background-hover",
"brique-hero-bouton-gauche-background-active", …
```

[SOIN] Transforme les boutons d'action de la brique hero en liens de redirection cliquables

---

package-lock.json
package.json
vite.config.ts

... En utilisant le bon fichier `.env` en fonction du mode pour `Histoire`, car par défaut, `histoire build` lance le fichier `vite.config` en mode `development`.
On s'assure donc que :
- Pour le BUILD : toujours en production
- Pour le DEV Histoire : en mode dev
- Pour le BUILD Histoire : en mode production

[CORRECTION] Rétablis le déploiement correct du Storybook

---

src/lib/Alerte.svelte

D’une part, la largeur autour de l’icône est corrigée pour toujours rester à 40px. D’autre part, on force l’alerte à ne jamais se réduire sous 200px.

Corrige les largeurs de l’alerte

---

src/lib/index.ts
src/lib/lab/vitrines-produits/briques/BriqueContenuADeuxColonnes.svelte
src/variables.scss
stories/OutilSelecteurTheme.svelte
stories/exemples-integration/LandingMAC.story.svelte
stories/lab/vitrines-produits/briques/BriqueContenuADeuxColonnes.story.svelte

Ajoute la brique de contenu à deux colonnes.
Le contenu de cette brique peut être réordonné (illustration à gauche, textes à droite OU vice versa)

[COMPOSANT] Brique réutilisable à deux colonnes

---

src/lib/lab/vitrines-produits/briques/CarrouselTuiles/CarrouselTuiles.svelte
src/lib/lab/vitrines-produits/briques/marelle/Etape.svelte
src/lib/lab/vitrines-produits/briques/temoignages/Temoignages.svelte

Pour : 
- Les boutons Suivant et Précédent du CarrouselTuiles et des Témoignages
- Les liens affichés dans les étapes de la Marelle
On a également réduit la taille du texte des boutons Suivant et Précédent avec l'équipe Design

[COMPOSANTS] Souligne les boutons représentant des liens dans les briques réutilisables

---

outils/extraction-props-composant.ts
outils/injection-nonce.ts
outils/vite-plugin-genere-jsx.ts
outils/vite-plugin-injecte-nonce.ts
tests/outils/extraction-props-composant.spec.ts
tests/outils/injection-nonce.spec.ts

... afin d'éviter l'utilisation trop fragile de regex.
On se base sur l'utilisation des compilateurs Svelte et Typescript afin d'analyser correctement les webcomponents générés.

[SOIN] Amélioration de la génération du fichier JSX

---

package-lock.json
package.json
src/lib/lab/blog/SommaireMobile.svelte

Le marqueur doit être caché avec un `list-style:none` sur Safari depuis la version 18.

Cache le marqueur du sommaire sur safari

---

package-lock.json
package.json
src/lib/lab/blog/IconeChevronBas.svelte
src/lib/lab/blog/IconeMenuLateral.svelte

... car ils peuvent être réduit si le titre du sommaire est long.

[CORRECTION] Empêche le rétrécissement des icônes du sommaire mobile

---

package-lock.json
package.json
src/lib/lab/Tag.svelte

Ceci pour éviter que l’événement click soit lancé deux fois par le bouton.

Corrige le comportement du clic sur un Tag

---

package-lock.json
package.json
src/lib/lab/Bouton.svelte
src/lib/lab/Lien.svelte
src/lib/lab/apparence-bouton.scss
stories/lab/Bouton.story.svelte
stories/lab/Lien.story.svelte

- ajoute l’état « désactivé » sur les boutons et les liens (en apparence de bouton)
- évite une double propagation des événements de clic sur les boutons

Améliore les boutons

---

package-lock.json
package.json
src/lib/lab/Tag.svelte
stories/lab/Tag.story.svelte

...via ses propriétés, en plus de son état interne.
Cela permet notamment, lorsque l'état "pressé" d'un tag est lié à un état serveur, et que cet état serveur peut évoluer indépendamment d'un clic sur le Tag, de synchroniser l'état du Tag et l'état serveur
Exemple : un composant Tag est utiliser pour filtrer un contenu, mais on peut également réinitialiser le filtre via un bouton "réinitialisation" dédié.

Pilote l'état "pressé" du composant Tag

---

src/lib/lab/Bouton.svelte
src/lib/lab/Icone.svelte
src/lib/lab/Lien.svelte
src/lib/lab/ResumePssi.svelte
src/lib/lab/Tag.svelte

Cette PR effectue l'ensemble des évolutions de code permettant de passer de Svelte 4 à Svelte 5, pour les composants suivants :
- Composant **Bouton**
- Composant **Icone**
- Composant **Lien**
- Composant **ResumePssi**
- Composant **Tag**

Migration des composants "Lab" en Svelte 5

---

src/lib/suite-cyber/navigation/BlocLiens.svelte
src/lib/suite-cyber/navigation/Navigation.svelte

Cette PR effectue l'ensemble des évolutions de code permettant de passer de Svelte 4 à Svelte 5, pour les composants suivants :
- Composant **BlocLiens**
- Composant **Navigation**

Migration des composants "Suite Cyber" en Svelte 5

---

src/lib/lab/vitrines-produits/briques/marelle/Etape.svelte
src/lib/lab/vitrines-produits/briques/marelle/Marelle.svelte

Cette PR effectue l'ensemble des évolutions de code permettant de passer de Svelte 4 à Svelte 5, pour les composants suivants :
- Composant **Etape**
- Composant **Marelle**

Migration des composants "Marelle" en Svelte 5

---

src/lib/Alerte.svelte
src/lib/CentreAide.svelte
src/lib/lab/icones/Fleche.svelte
src/lib/lab/icones/LienExterne.svelte
src/lib/pied-de-page/NavigationPiedDePage.svelte
stories/ConteneurStory.svelte

Cette PR effectue l'ensemble des évolutions de code permettant de passer de Svelte 4 à Svelte 5, pour les composants suivants :
- Composant **Alerte**
- Composant **CentreAide**
- Composant **Fleche**
- Composant **LienExterne**
- Composant **NavigationPiedDePage**
- Composant  **ConteneurStory**

Migration des composants transverses en Svelte 5

---

.storybook/main.ts

La commande `npm run storybook:dev` ne semble plus fonctionner correctement suite aux récents changements sur le projet.
Cette PR rétabli le lancement de Storybook en dev.

[CORRECTION] Rétablis le lancement de Storybook en dev

---

package-lock.json
package.json
src/lib/dsfr/DsfrSideMenu.svelte

Le fonctionnement interne du `DsfrSideMenu` se repose sur un `document.getElementById` qui ne fonctionne pas dans un shadowRoot. Nous proposons de se baser sur une référence interne avec un `bind:this`

[BUG] Corrige le menu latéral DSFR

---

package-lock.json
package.json
src/lib/dsfr/DsfrSideMenu.svelte
stories/dsfr/SideMenu.stories.svelte

Corrige la régression introduite en 1.28.2 sur le dépliage des sous menu
Et implémente le comportement du DSFR visant à replier automatiquement les menus de même niveau lorsqu'on clique sur un menu

[MENU-LATERAL] Corrige side menu

---

src/lib/dsfr/DsfrCheckboxesGroup.svelte
src/lib/dsfr/DsfrRadiosGroup.svelte

L'override des styles de la la balise `fieldset` effectuée dans des précédents commits ([ici](https://github.com/betagouv/lab-anssi-ui-kit/commit/23a848bcd36b4366695eb32638e3483a26a55a6f) & [ici](https://github.com/betagouv/lab-anssi-ui-kit/commit/ed6352b75ce1e6a3e9be3d45444f123cfc2e1362)) posent un problème d'affichage dans les composants `DsfrCheckboxesGroup` & `DsfrRadiosGroup` pour leurs variations `valid` et `error` _(cf: screenshot)_.
Cette PR effectue donc un rollback sur ces modifications afin de conserver le style par défaut des composants.
Une prochaine PR s'attachera à résoudre le pb qui a conduit à ces overrides, sans doute à faire côté DSC.

[BUG] Annulation de l'override des styles des fieldsets

---

.github/workflows/publication-npm.yml

La commande `s3cmd` utilisait `guess-mime-type` qui ne semble pas fonctionner pour des fichiers CSS.
On force donc le type à la main.

[CORRECTION] Force les `mime-type` pour les assets déployés sur le S3

---

package.json
src/lib/styles/dsfr-variables.scss

Suite à la [mise à disposition des variables CSS du DSFR](https://github.com/betagouv/lab-anssi-ui-kit/pull/202) directement dans le S3, l'erreur suivante apparait lors de la consommation de ce fichier : 
```
Refused to connect to '/dsfr-variables.css.map' because it violates the following Content Security Policy directive: "connect-src 'self'
```
Cela est dû au fait que par défaut Sass génère un fichier de mapping `.map` en plus du fichier `.css`.
Le lien vers ce fichier est contenu dans le fichier `.css` via la ligne suivante : `/*# sourceMappingURL=dsfr-variables.css.map */`.
Hors nous ne publions pas ce fichier de mapping sur le S3.
En vu de corriger ce problème cette PR effectue deux choses : 
- La création d'un fichier `dsfr-variables.scss` qui importe les variables en provenance du …

[SASS] - DSFR Variables - Désactive la génération du fichier source map

---

src/lib/dsfr/DsfrAlert.svelte
src/lib/dsfr/DsfrButton.svelte

Suite à [un précédent commit](https://github.com/betagouv/lab-anssi-ui-kit/commit/00c4c9b98bf4b476f28274e5bba9644969d6030e) concernant l'import de façon unitaire des styles uniquement nécessaires aux composants, les styles de certaines variations n'ont pas été importés. 
Cette PR corrige cela pour les composants : 
- `DsfrAlert` : Ajoute les styles permettant de gérer la variation "fermable"
- `DsfrButton` : Ajoute les styles permettant de gérer la variation `lien` + un correctif concernant la valeur de l'attribut `target`

[COMPOSANTS] - DSFR - Améliore l'affichage des boutons

---

src/lib/dsfr/DsfrCheckbox.svelte

Remonte l'état "coché" du composant `DsfrCheckbox` dans l'évenement `valuechanged`

[BUG] Remonte l'état 'coché' du composant DsfrCheckbox
